name: money_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  melos: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  husky: ^0.1.7
  lint_staged: ^0.5.1

flutter:
  uses-material-design: true

lint_staged:
  "**/*.dart": dart format -l 80 && dart analyze --fatal-infos --fatal-warnings
