name: money_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  melos: ^6.3.2
  flutter_screenutil: ^5.9.3
  ui:
    path: modules/ui
  core:
    path: modules/core
  auth:
    path: modules/auth
  user:
    path: modules/user

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  husky: ^0.1.7
  lint_staged: ^0.5.1
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod
    - .env.staging
    - ./assets/images/
  fonts:
    - family: LineSeedSansTH
      fonts:
        - asset: ./assets/fonts/LINESeedSansTH_A_Rg.ttf
          weight: 400
        - asset: ./assets/fonts/LINESeedSansTH_A_Bd.ttf
          weight: 500

lint_staged:
  "**/*.dart": dart format -l 80 && dart analyze --fatal-infos --fatal-warnings

flutter_gen:
  output: ./modules/core/lib/src/generated
  assets:
    exclude:
      - .env.dev
      - .env.prod
      - .env.staging
