// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:shared/libs.dart';
import 'package:shared/shared.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LocaleModelAdapter());
    registerAdapter(SessionModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(LocaleModelAdapter());
    registerAdapter(SessionModelAdapter());
  }
}
