name: core
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.2.1
  flutter_form_builder: ^10.0.1
  flutter_hooks: ^0.20.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  form_builder_validators: ^11.1.2
  get_it: ^8.0.3
  go_router: ^15.1.2
  hive_flutter: ^1.1.0
  hooked_bloc: ^1.5.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  ua_client_hints: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.10.0

flutter:
